name: rust
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install package
        run: |
          sudo apt install -y protobuf-compiler
      - name: cargo test
        run: |
          cargo build --all-features
          cargo test

      - name: cargo format check
        run: |
          cargo fmt --check