name: rust
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo test
        run: |
          cargo build --debug --all-features
          cargo test
          cargo fmt --check

      - name: cargo format check
        run: |
          cargo fmt --check